###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '2.0'
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:latest'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        restart: always
        volumes:
            - './mysql-service/init:/docker-entrypoint-initdb.d/'
        ports:
            - '3306:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './www:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:8080'
            
    php-fpm:
        build: phpdocker/php-fpm
        container_name: comment_serve
        working_dir: /application
        volumes:
            - './www:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
